import { poppins } from "../components/ui/fonts";

import Footer from "@/components/layout/footer/footer";
import Header from "../components/layout/header/header";

import "boxicons/css/boxicons.min.css";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";

import HeaderDataFetchWrapper from "@/components/layout/header/header-data-fetch-wrapper";
import QueryProvider from "@/store/query-client-provider";
import StoreProvider from "@/store/store-provider";
import "../components/ui/globals.css";
import AuthModal from "@/components/layout/modals/auth-modal";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import BasicDetailModal from "@/components/layout/modals/basic-detail-modal";
import "../components/car-module/car-style.css";

import Script from "next/script";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // ✅ WebPage Schema
  const webpageSchema = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Discover & Purchase New Cars in India | CarOnPhone",
    description:
      "Find your dream car on CarOnPhone. Discover new models, read reviews, and stay updated on Tata, Maruti, Toyota, Hyundai, and more. Book a test drive now!",
    url: "https://caronphone.com/",
    publisher: {
      "@type": "Organization",
      name: "CarOnPhone",
      logo: {
        "@type": "ImageObject",
        url: "https://caronphone.com/favicon.ico",
      },
    },
  };
  return (
    <html lang="en">
      <head>
        {process.env.NEXT_SITE_URL == "https://caronphone.com" ? (
          <>
            {/* ahrefs */}
            {/* <Script
              src="https://analytics.ahrefs.com/analytics.js"
              data-key="LiNR0FsCk0jNb2q62YxJcA"
              async
            ></Script> */}
            {/* GTM */}
            <Script id="gtm-script" strategy="beforeInteractive">
              {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-P65SJ94H');
          `}
            </Script>
            {/* Hotjar Tracking Code for https://caronphone.com/ */}
            {/* <Script>
              {`(function(h, o, t, j, a, r) {
                h.hj = h.hj || function() {
                    (h.hj.q = h.hj.q || []).push(arguments)
                };
                h._hjSettings = {
                    hjid: 4988983,
                    hjsv: 6
                };
                a = o.getElementsByTagName('head')[0];
                r = o.createElement('script');
                r.async = 1;
                r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
                a.appendChild(r);
            })(window, document, 'https://static.hotjar.com/c/hotjar-', '.js?sv=');`}
            </Script> */}
            <meta name="robots" content="index, follow" />
          </>
        ) : (
          <meta name="robots" content="noindex, nofollow" />
        )}

        <link rel="icon" type="image/png" href="/favicon.png" />
        <meta name="theme-color" content="#0177aa" />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="CarOnPhone" />
        <meta name="apple-mobile-web-app-title" content="CarOnPhone" />
        <meta name="msapplication-navbutton-color" content="#0177aa" />
        <meta name="author" content="CarOnPhone" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="msapplication-starturl" content="/" />
        <meta name="msvalidate.01" content="39BC138BC872BEE9A3EEB7D5BB427267" />
        {/* ✅ Inject Schema Markups */}
        <Script id="schema-webpage" type="application/ld+json">
          {JSON.stringify(webpageSchema)}
        </Script>
      </head>
      <body
        className={`${poppins.className} antialiased flex flex-col bg-theme-background selection:bg-sky-100 selection:text-sky-600`}
      >
        {/* ✅ GTM <noscript> at top of <body> */}
        {process.env.NEXT_SITE_URL == "https://caronphone.com" ? (
          <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-P65SJ94H"
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            ></iframe>
          </noscript>
        ) : null}
        <StoreProvider>
          <QueryProvider>
            <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              draggable
              theme="dark"
            />
            <HeaderDataFetchWrapper>
              <Header />
            </HeaderDataFetchWrapper>
            <AuthModal />
            <BasicDetailModal />

            <main>{children}</main>
            <Footer />
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
